project:
  type: manuscript
  output-dir: docs
  render:
    - index.qmd

manuscript:
  article: index.qmd
  notebooks:
    - notebook: continuous-time.qmd

format:
  html:
    toc: true
    toc-location: right
  pdf: default
  docx: default

execute:
  freeze: true

bibliography: references.bib
keywords: "video games, well-being, mood, play behavior, telemetry"
csl: apa.csl

author:
  - name: Matti Vuorre
    orcid: 0000-0001-5052-066X
    email: mjvuorre@uvt.nl
    url: https://vuorre.netlify.app
    affiliation:
      - ref: a
      - ref: b
  - name: Nick Ballou
    orcid: 0000-0003-4126-0696
    affiliation:
      - ref: b
  - name: Thomas Hakman
    affiliation:
      - ref: b
  - name: Kristoffer Magnusson
    orcid: 0000-0003-0713-0556
    url: https://rpsychologist.com
    affiliation:
      - ref: b
      - ref: c
  - name: Andrew K. Przybylski
    orcid: 0000-0001-5547-2185
    affiliation:
      - ref: b

affiliations:
  - id: a
    name: Tilburg University
    department: Tilburg School of Social and Behavioral Science
  - id: b
    name: University of Oxford
    department: Oxford Internet Institute
  - id: c
    name: Karolinska Institutet
