title: "Mood increases during video game play: A naturalistic observational case study of PowerWash Simulator"
description: Computational notebook supporting our manuscript

project:
  render:
    - wrangle.qmd
    - analyze.qmd
    - continuous-time.qmd

author:
  - name: Matti Vuorre
    orcid: 0000-0001-5052-066X
    email: mjvuorre@uvt.nl
    url: https://vuorre.netlify.app
    affiliation:
      - ref: a
      - ref: b
  - name: Kristoffer Magnusson
    orcid: 0000-0003-0713-0556
    email: kristoffer.magnusson@ki.se
    url: https://rpsychologist.com
    affiliation:
      - ref: b
      - ref: c
  - name: Nick Ballou
    orcid: 0000-0003-4126-0696
    affiliation:
      - ref: b
  - name: Andrew K. Przybylski
    orcid: 0000-0001-5547-2185
    affiliation:
      - ref: b
affiliations:
  - id: a
    name: Tilburg University
  - id: b
    name: University of Oxford
  - id: c
    name: Karolinska Institutet

date: 2023-09-19
bibliography: bibliography.bib
format:
  html:
    code-fold: true
    toc: true
    toc-depth: 2
